# Generated by Django 3.1.3 on 2020-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_short', models.CharField(max_length=200)),
                ('the_long', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ace_comp', models.TextField()),
                ('ace_comp_res', models.TextField()),
                ('get_proj', models.TextField()),
                ('get_proj_res', models.TextField()),
                ('get_jobs', models.TextField()),
                ('get_jobs_res', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_header', models.CharField(default='Project for a Techie', max_length=200)),
                ('project_body', models.TextField()),
                ('amount', models.CharField(default='100', max_length=100)),
                ('bargain', models.CharField(choices=[('negotiable', 'NEGOTIABLE'), ('fixed', 'FIXED')], default='negotiable', max_length=20)),
                ('location', models.TextField()),
                ('contact_me', models.TextField()),
            ],
        ),
    ]
