# Generated by Django 3.1.3 on 2020-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverSkilledApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='applied',
            field=models.IntegerField(default=0),
        ),
    ]
