# Generated by Django 3.1.3 on 2020-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverSkilledApp', '0002_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('specialization', models.TextField()),
                ('prize', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('url', models.TextField()),
            ],
        ),
    ]
