# Generated by Django 3.1.3 on 2020-12-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverSkilledApp', '0002_competition_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_header', models.CharField(max_length=200)),
                ('job_body', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('amount', models.CharField(default='100', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact_me', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('applied', models.IntegerField(default=0)),
            ],
        ),
    ]
