# Generated by Django 3.1.3 on 2020-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverSkilledApp', '0004_auto_20201214_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
