# Generated by Django 3.1.3 on 2020-12-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverSkilledApp', '0005_auto_20201222_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='category',
        ),
    ]
